tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "bat"
brew "colordiff"
brew "exa"
brew "git"
brew "gnu-sed"
brew "hadolint"
brew "helm"
brew "hey"
brew "hub"
brew "jq"
brew "nginx"
brew "redis", restart_service: true
brew "supervisor", restart_service: true
brew "telnet"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "yq"
brew "zsh"
cask "font-jetbrains-mono"
cask "google-cloud-sdk"
